# -*- coding: utf-8 -*-
"""01_Setup_and_Degradation(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CegRoJ4RMxx-gTK_3PEkbsCz0-oPfQFZ

# 🛰️ Notebook 1 — Setup & Degradation Pipeline
**Paper:** *A Corruption-Aware Image Restoration Framework for Spaceborne Optical Navigation*

This notebook:
1. Mounts Google Drive and sets up all paths
2. Installs required libraries
3. Runs the full degradation pipeline on SPEED+ images
   - **Super-Resolution:** bicubic downsampling (×4)
   - **Inpainting:** random binary mask generation
4. Visualises and saves degraded pairs to Drive

---
> ⚡ **Runtime:** `Runtime → Change runtime type → T4 GPU`

## 📁 Step 1 — Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os

DRIVE_ROOT      = '/content/drive/MyDrive'
SPEEDPLUS_DIR   = f'{DRIVE_ROOT}/speed/' # SPEED+ images
PROJECT_DIR     = f'{DRIVE_ROOT}/space_restoration'
# ────────────────────────────────────────────────────────────────────────────

SR_LR_DIR      = f'{PROJECT_DIR}/sr/lr'
SR_HR_DIR      = f'{PROJECT_DIR}/sr/hr'
INP_GT_DIR     = f'{PROJECT_DIR}/inpaint/gt'
INP_MASK_DIR   = f'{PROJECT_DIR}/inpaint/masks'
INP_MASKED_DIR = f'{PROJECT_DIR}/inpaint/masked'

for d in [SR_LR_DIR, SR_HR_DIR, INP_GT_DIR, INP_MASK_DIR, INP_MASKED_DIR]:
    os.makedirs(d, exist_ok=True)

imgs = [f for f in os.listdir(SPEEDPLUS_DIR) if f.endswith(('.jpg','.png'))]
print(f'✅ Found {len(imgs)} SPEED+ images in {SPEEDPLUS_DIR}')

"""## 📦 Step 2 — Install Libraries"""

!pip install -q opencv-python-headless Pillow numpy matplotlib tqdm
print('✅ Libraries ready')

"""## 🔧 Step 3 — Degradation Functions"""

import random
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


IMG_SIZE      = 256
SR_SCALE      = 4     # Downsampling factor for super-resolution

MASK_N_MIN    = 1
MASK_N_MAX    = 2
MASK_MIN_RECT = 20
MASK_MAX_RECT = 80    spacecraft
MASK_MAX_COVERAGE = 0.30

MAX_IMAGES    = None  #
# ─────────────────────────────────────────────────────────────────────────────


def load_and_resize(path: str, size: int = IMG_SIZE) -> Image.Image:
    """Load an image from disk, convert to RGB, resize."""
    return Image.open(path).convert('RGB').resize((size, size), Image.BICUBIC)


# ── Super-Resolution degradation ─────────────────────────────────────────────
def make_lr(hr: Image.Image, scale: int = SR_SCALE) -> Image.Image:
    """
    Bicubic downsampling to simulate limited sensor resolution.
    hr  : high-resolution PIL Image
    Returns low-resolution PIL Image (hr.size // scale)
    """
    w, h = hr.size
    return hr.resize((w // scale, h // scale), Image.BICUBIC)


# ── Inpainting mask generators ────────────────────────────────────────────────
def make_rect_mask(h: int, w: int) -> np.ndarray:
    """
    Conservative spacecraft mask: 1–2 rectangles, hard-capped at 30% total coverage.
    Simulates sensor dropout or partial debris occlusion without destroying
    the spacecraft silhouette needed for pose estimation.
    """
    mask      = np.zeros((h, w), dtype=np.float32)
    max_pixels = int(h * w * MASK_MAX_COVERAGE)
    n = random.randint(MASK_N_MIN, MASK_N_MAX)

    for _ in range(n):
        # Stop adding rectangles if coverage cap already reached
        if mask.sum() >= max_pixels:
            break

        rh = random.randint(MASK_MIN_RECT, min(MASK_MAX_RECT, h))
        rw = random.randint(MASK_MIN_RECT, min(MASK_MAX_RECT, w))

        # Place preferentially near image edges (less likely to hit spacecraft centre)
        edge_bias = random.random()
        if edge_bias < 0.5:
            # Edge placement
            top  = random.choice([0, h - rh])
            left = random.randint(0, w - rw)
        else:
            # Free placement anywhere
            top  = random.randint(0, h - rh)
            left = random.randint(0, w - rw)

        # Only place if it won't push us over the coverage cap
        candidate = np.zeros_like(mask)
        candidate[top:top+rh, left:left+rw] = 1.0
        if mask.sum() + candidate.sum() <= max_pixels:
            mask = np.clip(mask + candidate, 0, 1)

    return mask


def make_irregular_mask(h: int, w: int) -> np.ndarray:
    """
    Irregular brush-stroke mask.
    Simulates debris trails, partial occlusions, or non-uniform sensor artifacts.
    """
    mask = np.zeros((h, w), dtype=np.float32)
    for _ in range(random.randint(5, 20)):
        x, y  = random.randint(0, w), random.randint(0, h)
        length = random.randint(20, 80)
        angle  = random.uniform(0, 2 * np.pi)
        thick  = random.randint(5, 25)
        for step in range(length):
            cx = int(x + step * np.cos(angle))
            cy = int(y + step * np.sin(angle))
            if 0 <= cx < w and 0 <= cy < h:
                r = thick // 2
                mask[max(0,cy-r):min(h,cy+r), max(0,cx-r):min(w,cx+r)] = 1.0
    return np.clip(mask, 0, 1)


def apply_mask(img_np: np.ndarray, mask: np.ndarray) -> np.ndarray:
    """Zero-out masked pixels. img_np: (H,W,3) float [0,1], mask: (H,W) {0,1}."""
    return img_np * (1.0 - mask[:, :, None])


print('✅ Degradation functions defined')

"""## 🔍 Step 4 — Preview Degradations (5 random samples)"""

sample_paths = random.sample(
    [os.path.join(SPEEDPLUS_DIR, f) for f in imgs if f.endswith(('.jpg','.png'))],
    min(5, len(imgs))
)

fig, axes = plt.subplots(5, 5, figsize=(18, 18))
col_labels = ['Original HR', 'LR (×4 down)', 'LR (Bicubic ↑)', 'Rect Mask', 'Masked Image']

for col, label in enumerate(col_labels):
    axes[0][col].set_title(label, fontsize=11, fontweight='bold', pad=8)

for row, path in enumerate(sample_paths):
    hr  = load_and_resize(path)
    lr  = make_lr(hr)
    lr_up = lr.resize((IMG_SIZE, IMG_SIZE), Image.BICUBIC)

    hr_np  = np.array(hr) / 255.0
    mask   = make_rect_mask(IMG_SIZE, IMG_SIZE)
    masked = apply_mask(hr_np, mask)

    mask_vis = np.stack([mask]*3, axis=-1)  # greyscale mask as RGB

    for col, img in enumerate([hr_np, np.array(lr)/255.0, np.array(lr_up)/255.0, mask_vis, masked]):
        axes[row][col].imshow(img if img.shape[-1]==3 else img, cmap='gray')
        axes[row][col].axis('off')

plt.suptitle('SPEED+ Degradation Preview', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig(f'{PROJECT_DIR}/degradation_preview.png', dpi=120, bbox_inches='tight')
plt.show()
print('✅ Preview saved to Drive')

"""## 💾 Step 5 — Run Full Degradation Pipeline & Save to Drive"""

from tqdm import tqdm

all_paths = sorted([os.path.join(SPEEDPLUS_DIR, f)
                    for f in os.listdir(SPEEDPLUS_DIR)
                    if f.endswith(('.jpg', '.png'))])

if MAX_IMAGES:
    all_paths = all_paths[:MAX_IMAGES]

print(f'Processing {len(all_paths)} images...')

for path in tqdm(all_paths, desc='Degradation pipeline'):
    stem = os.path.splitext(os.path.basename(path))[0]

    # ── Load & resize ────────────────────────────────────────────────────────
    hr  = load_and_resize(path, IMG_SIZE)
    hr_np = np.array(hr, dtype=np.float32) / 255.0

    # ── Super-Resolution pair ────────────────────────────────────────────────
    lr = make_lr(hr, SR_SCALE)
    hr.save(f'{SR_HR_DIR}/{stem}.png')
    lr.save(f'{SR_LR_DIR}/{stem}.png')

    # ── Inpainting pair (mixed: 50% rect, 50% irregular) ─────────────────────
    if random.random() > 0.5:
        mask = make_rect_mask(IMG_SIZE, IMG_SIZE)
    else:
        mask = make_irregular_mask(IMG_SIZE, IMG_SIZE)

    masked = apply_mask(hr_np, mask)

    hr.save(f'{INP_GT_DIR}/{stem}.png')
    Image.fromarray((mask * 255).astype(np.uint8)).save(f'{INP_MASK_DIR}/{stem}.png')
    Image.fromarray((masked * 255).astype(np.uint8)).save(f'{INP_MASKED_DIR}/{stem}.png')

print('\n✅ Degradation complete!')
print(f'   SR pairs  → {SR_LR_DIR}')
print(f'   Inpainting → {INP_GT_DIR}')

"""## ✅ Summary

| Output | Location |
|--------|----------|
| SR — HR images | `space_restoration/sr/hr/` |
| SR — LR images | `space_restoration/sr/lr/` |
| Inpaint — GT   | `space_restoration/inpaint/gt/` |
| Inpaint — Masks | `space_restoration/inpaint/masks/` |
| Inpaint — Masked | `space_restoration/inpaint/masked/` |

➡️ **Next:** Open `02_SuperResolution_SwinIR.ipynb`
"""