# -*- coding: utf-8 -*-
"""02_SuperResolution_SwinIR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4e_gkAU4EalqjQgAXy-cmF_NGpNSMyp

# 🔭 Notebook 2 — Super-Resolution with SwinIR
**Paper:** *A Corruption-Aware Image Restoration Framework for Spaceborne Optical Navigation*

This notebook:
1. Loads the LR/HR pairs created in Notebook 1
2. Downloads pretrained SwinIR weights
3. Fine-tunes SwinIR on SPEED+ data
4. Evaluates with PSNR & SSIM
5. Saves qualitative comparison grids to Drive

---
> ⚡ **Runtime:** `Runtime → Change runtime type → T4 GPU`

## 📁 Step 1 — Mount Drive & Set Paths
"""

from google.colab import drive
drive.mount('/content/drive')

import os

DRIVE_ROOT   = '/content/drive/MyDrive'
PROJECT_DIR  = f'{DRIVE_ROOT}/space_restoration'
SR_LR_DIR    = f'{PROJECT_DIR}/sr/lr'
SR_HR_DIR    = f'{PROJECT_DIR}/sr/hr'
CKPT_DIR     = f'{PROJECT_DIR}/checkpoints/swinir'
VIS_DIR      = f'{PROJECT_DIR}/visuals/swinir'
# ─────────────────────────────────────────────────────────────────────────────

os.makedirs(CKPT_DIR, exist_ok=True)
os.makedirs(VIS_DIR,  exist_ok=True)

n_lr = len(os.listdir(SR_LR_DIR))
n_hr = len(os.listdir(SR_HR_DIR))
print(f'✅ Found {n_lr} LR images and {n_hr} HR images')

from google.colab import drive
drive.mount('/content/drive')

"""## 📦 Step 2 — Install Dependencies & Clone SwinIR"""

!pip install -q timm einops

import os
if not os.path.exists('/content/SwinIR'):
    !git clone https://github.com/JingyunLiang/SwinIR.git /content/SwinIR
    print('✅ SwinIR cloned')
else:
    print('✅ SwinIR already present')

import sys
sys.path.insert(0, '/content/SwinIR')

"""## ⬇️ Step 3 — Download Pretrained SwinIR Weights (×4 Classical SR)"""

import urllib.request

PRETRAINED_PATH = '/content/swinir_sr_x4.pth'
WEIGHTS_URL = ('https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/'
               '001_classicalSR_DIV2K_s48w8_SwinIR-M_x4.pth')

if not os.path.exists(PRETRAINED_PATH):
    print('Downloading pretrained weights...')
    urllib.request.urlretrieve(WEIGHTS_URL, PRETRAINED_PATH)
    print('✅ Weights downloaded')
else:
    print('✅ Weights already cached')

"""## 🗂️ Step 4 — Dataset & DataLoader"""

import random
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms.functional as TF

IMG_SIZE   = 256    # HR size
SR_SCALE   = 4
BATCH_SIZE = 4
VAL_SPLIT  = 0.1   # 10% of images for validation
SEED       = 42
# ─────────────────────────────────────────────────────────────────────────────

random.seed(SEED)
torch.manual_seed(SEED)


class SRDataset(Dataset):
    def __init__(self, lr_dir, hr_dir, augment=True):
        self.lr_paths = sorted([os.path.join(lr_dir, f)
                                 for f in os.listdir(lr_dir)
                                 if f.endswith(('.png', '.jpg'))])
        self.hr_dir  = hr_dir
        self.augment = augment

    def __len__(self):
        return len(self.lr_paths)

    def __getitem__(self, idx):
        lr_path = self.lr_paths[idx]
        hr_path = os.path.join(self.hr_dir, os.path.basename(lr_path))

        lr = Image.open(lr_path).convert('RGB')
        hr = Image.open(hr_path).convert('RGB')

        # Augmentation
        if self.augment:
            if random.random() > 0.5:
                lr, hr = TF.hflip(lr), TF.hflip(hr)
            if random.random() > 0.5:
                lr, hr = TF.vflip(lr), TF.vflip(hr)

        lr_t = TF.to_tensor(lr)  # [3, H/4, W/4]
        hr_t = TF.to_tensor(hr)  # [3, H, W]
        return lr_t, hr_t, os.path.splitext(os.path.basename(lr_path))[0]


# Train / Val split
all_files = sorted([f for f in os.listdir(SR_LR_DIR) if f.endswith(('.png','.jpg'))])
random.shuffle(all_files)
n_val   = max(1, int(len(all_files) * VAL_SPLIT))
val_files   = all_files[:n_val]
train_files = all_files[n_val:]

# Save split lists
def write_split(files, path):
    with open(path, 'w') as f:
        f.writelines(fn + '\n' for fn in files)

write_split(train_files, f'{PROJECT_DIR}/sr_train_split.txt')
write_split(val_files,   f'{PROJECT_DIR}/sr_val_split.txt')

train_ds = SRDataset(SR_LR_DIR, SR_HR_DIR, augment=True)
val_ds   = SRDataset(SR_LR_DIR, SR_HR_DIR, augment=False)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=1,          shuffle=False, num_workers=2)

print(f'✅ Train: {len(train_ds)} images | Val: {len(val_ds)} images')

"""## 🧠 Step 5 — Load SwinIR Model & Pretrained Weights"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from models.network_swinir import SwinIR

DEVICE      = 'cuda' if torch.cuda.is_available() else 'cpu'
WINDOW_SIZE = 8
print(f'Device: {DEVICE}')

ckpt  = torch.load(PRETRAINED_PATH, map_location=DEVICE)
state = ckpt.get('params', ckpt)

_embed_dim = state['conv_first.weight'].shape[0]                          # 180

_n_layers  = max(int(k.split('.')[1]) for k in state if k.startswith('layers.')) + 1  # 6

_num_heads = _embed_dim // 30                                              # 6

_attn_windows = state['layers.0.residual_group.blocks.1.attn_mask'].shape[0]  # 36
_img_size     = int(_attn_windows ** 0.5) * WINDOW_SIZE                        # 48

print(f'Checkpoint config:  embed_dim={_embed_dim}, n_layers={_n_layers}, '
      f'num_heads={_num_heads}, img_size={_img_size}')

#  Build model with the EXACT config from checkpoint
model = SwinIR(
    upscale         = SR_SCALE,
    in_chans        = 3,
    img_size        = _img_size,       # 48  —
    window_size     = WINDOW_SIZE,     # 8
    img_range       = 1.0,
    depths          = [6] * _n_layers,
    embed_dim       = _embed_dim,
    num_heads       = [_num_heads] * _n_layers,
    mlp_ratio       = 2,
    upsampler       = 'pixelshuffle',
    resi_connection = '1conv'
).to(DEVICE)

#  Load weights
missing, unexpected = model.load_state_dict(state, strict=True)
print(f'✅ Weights loaded — 0 mismatches expected')

n_params = sum(p.numel() for p in model.parameters()) / 1e6
print(f'✅ SwinIR-M ready — {n_params:.1f}M parameters')


#  pad input to multiple of window_size, then crop
def pad_to_window(x, window_size=WINDOW_SIZE):
    """Pad spatial dims so H and W are multiples of window_size."""
    _, _, h, w = x.shape
    pad_h = (window_size - h % window_size) % window_size
    pad_w = (window_size - w % window_size) % window_size
    return F.pad(x, (0, pad_w, 0, pad_h), mode='reflect'), h, w

def run_swinir(model, lr_batch, scale=SR_SCALE):
    """Run SwinIR with automatic padding/cropping for any input size."""
    x, h, w = pad_to_window(lr_batch)
    out = model(x)
    return out[:, :, :h*scale, :w*scale]   # crop to original HR size

print('✅ run_swinir() helper defined — handles any input resolution')

"""## 🏋️ Step 6 — Training Loop"""

import math
import time
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR

#  Hyperparameters
NUM_EPOCHS = 100
LR         = 2e-4
PATIENCE   = 15     # Early-stopping patience (epochs)
SAVE_EVERY = 10
#

criterion = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=LR, betas=(0.9, 0.999))
scheduler = CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS, eta_min=1e-7)


def calc_psnr(pred, gt, max_val=1.0):
    mse = torch.mean((pred - gt) ** 2).item()
    return 10 * math.log10(max_val**2 / mse) if mse > 1e-10 else float('inf')


def validate(model, loader):
    model.eval()
    total_psnr, total_loss = 0, 0
    with torch.no_grad():
        for lr_t, hr_t, _ in loader:
            lr_t, hr_t = lr_t.to(DEVICE), hr_t.to(DEVICE)
            pred = run_swinir(model, lr_t)
            pred = torch.clamp(pred, 0, 1)
            total_loss += criterion(pred, hr_t).item()
            total_psnr += calc_psnr(pred, hr_t)
    n = len(loader)
    return total_loss / n, total_psnr / n


history = {'train_loss': [], 'val_loss': [], 'val_psnr': []}
best_psnr   = 0
no_improve  = 0

print(f'Starting training for up to {NUM_EPOCHS} epochs...')
print(f'{"Epoch":>6}  {"Train Loss":>10}  {"Val Loss":>9}  {"Val PSNR":>9}  {"LR":>10}  {"Time":>7}')
print('-' * 65)

for epoch in range(1, NUM_EPOCHS + 1):
    model.train()
    t0 = time.time()
    train_loss = 0

    for lr_t, hr_t, _ in train_loader:
        lr_t, hr_t = lr_t.to(DEVICE), hr_t.to(DEVICE)
        optimizer.zero_grad()
        pred = run_swinir(model, lr_t)
        loss = criterion(pred, hr_t)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    train_loss /= len(train_loader)
    val_loss, val_psnr = validate(model, val_loader)
    scheduler.step()

    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['val_psnr'].append(val_psnr)

    elapsed = time.time() - t0
    lr_now  = scheduler.get_last_lr()[0]
    print(f'{epoch:>6}  {train_loss:>10.4f}  {val_loss:>9.4f}  {val_psnr:>9.2f}  {lr_now:>10.2e}  {elapsed:>6.1f}s')

    # Save best
    if val_psnr > best_psnr:
        best_psnr  = val_psnr
        no_improve = 0
        torch.save({'epoch': epoch, 'state_dict': model.state_dict(),
                    'psnr': best_psnr, 'optimizer': optimizer.state_dict()},
                   f'{CKPT_DIR}/swinir_best.pth')
        print(f'  💾 Best model saved  (PSNR {best_psnr:.2f} dB)')
    else:
        no_improve += 1

    # Periodic checkpoint
    if epoch % SAVE_EVERY == 0:
        torch.save({'epoch': epoch, 'state_dict': model.state_dict()},
                   f'{CKPT_DIR}/swinir_epoch{epoch}.pth')

    # Early stopping
    if no_improve >= PATIENCE:
        print(f'\n⏹  Early stopping at epoch {epoch} (no improvement for {PATIENCE} epochs)')
        break

print(f'\n✅ Training complete. Best Val PSNR: {best_psnr:.2f} dB')

"""## 📊 Step 7 — Training Curves"""

import matplotlib.pyplot as plt

epochs = range(1, len(history['train_loss']) + 1)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))

ax1.plot(epochs, history['train_loss'], label='Train Loss', color='steelblue')
ax1.plot(epochs, history['val_loss'],   label='Val Loss',   color='tomato')
ax1.set_xlabel('Epoch'); ax1.set_ylabel('L1 Loss')
ax1.set_title('SwinIR — Loss Curves'); ax1.legend(); ax1.grid(alpha=0.3)

ax2.plot(epochs, history['val_psnr'], color='seagreen')
ax2.axhline(best_psnr, ls='--', color='red', label=f'Best {best_psnr:.2f} dB')
ax2.set_xlabel('Epoch'); ax2.set_ylabel('PSNR (dB)')
ax2.set_title('SwinIR — Validation PSNR'); ax2.legend(); ax2.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(f'{PROJECT_DIR}/swinir_training_curves.png', dpi=120)
plt.show()
print('✅ Curves saved to Drive')

"""## 🖼️ Step 8 — Qualitative Results (Comparison Grid)"""

# Load best checkpoint
ckpt = torch.load(f'{CKPT_DIR}/swinir_best.pth', map_location=DEVICE)
model.load_state_dict(ckpt['state_dict'])
model.eval()

sample_loader = DataLoader(val_ds, batch_size=1, shuffle=True)
samples = []
with torch.no_grad():
    for lr_t, hr_t, name in sample_loader:
        pred = run_swinir(model, lr_t.to(DEVICE)).cpu().clamp(0, 1)
        samples.append((lr_t[0], pred[0], hr_t[0], name[0]))
        if len(samples) == 6:
            break

def t2np(t):
    return t.permute(1, 2, 0).numpy()

fig, axes = plt.subplots(6, 3, figsize=(12, 24))
for col, lbl in enumerate(['LR Input (Bicubic ↑)', 'SwinIR Output', 'Ground Truth HR']):
    axes[0][col].set_title(lbl, fontsize=11, fontweight='bold')

for row, (lr_t, pred_t, hr_t, name) in enumerate(samples):
    hr_size = (IMG_SIZE, IMG_SIZE)
    lr_up = t2np(torch.nn.functional.interpolate(
        lr_t.unsqueeze(0), size=hr_size, mode='bicubic', align_corners=False)[0])
    pred_np = t2np(pred_t)
    hr_np   = t2np(hr_t)

    psnr_val = calc_psnr(pred_t.unsqueeze(0), hr_t.unsqueeze(0))

    for col, (img, label) in enumerate(zip(
        [lr_up, pred_np, hr_np],
        ['LR', f'SwinIR\nPSNR={psnr_val:.2f}dB', 'GT']
    )):
        axes[row][col].imshow(img.clip(0, 1))
        axes[row][col].set_title(label, fontsize=8)
        axes[row][col].axis('off')

plt.suptitle('SwinIR Super-Resolution — SPEED+ Qualitative Results',
             fontsize=13, fontweight='bold', y=1.002)
plt.tight_layout()
plt.savefig(f'{VIS_DIR}/swinir_qualitative.png', dpi=120, bbox_inches='tight')
plt.show()
print('✅ Qualitative results saved')

"""## 📋 Step 9 — Full Quantitative Evaluation Table"""

import math, csv
from skimage.metrics import structural_similarity as skssim

model.eval()
results = []

with torch.no_grad():
    for lr_t, hr_t, name in val_loader:
        pred = run_swinir(model, lr_t.to(DEVICE)).cpu().clamp(0, 1)
        # Bicubic baseline
        bicubic = torch.nn.functional.interpolate(
            lr_t, size=(IMG_SIZE, IMG_SIZE), mode='bicubic', align_corners=False).clamp(0, 1)

        pred_np    = pred[0].permute(1,2,0).numpy()
        hr_np      = hr_t[0].permute(1,2,0).numpy()
        bicubic_np = bicubic[0].permute(1,2,0).numpy()

        mse_pred = np.mean((pred_np - hr_np)**2)
        mse_bic  = np.mean((bicubic_np - hr_np)**2)

        results.append({
            'name':          name[0],
            'psnr_bicubic':  10*math.log10(1/mse_bic)  if mse_bic > 1e-10 else 100,
            'psnr_swinir':   10*math.log10(1/mse_pred)  if mse_pred > 1e-10 else 100,
            'ssim_bicubic':  skssim(bicubic_np, hr_np, data_range=1.0, channel_axis=2),
            'ssim_swinir':   skssim(pred_np,    hr_np, data_range=1.0, channel_axis=2),
        })

avg = {k: np.mean([r[k] for r in results]) for k in results[0] if k != 'name'}

print('\n' + '='*55)
print('  Super-Resolution Evaluation (SPEED+ Validation Set)')
print('='*55)
print(f'  {'Model':<20} {'PSNR (dB)':>10} {'SSIM':>10}')
print('-'*45)
print(f'  {'Bicubic Upsampling':<20} {avg["psnr_bicubic"]:>10.2f} {avg["ssim_bicubic"]:>10.4f}')
print(f'  {'SwinIR (Fine-Tuned)':<20} {avg["psnr_swinir"]:>10.2f} {avg["ssim_swinir"]:>10.4f}')
print('='*55)

# Save CSV
csv_path = f'{PROJECT_DIR}/sr_results.csv'
with open(csv_path, 'w', newline='') as f:
    w = csv.DictWriter(f, fieldnames=results[0].keys())
    w.writeheader(); w.writerows(results)
print(f'\n✅ Per-image results saved → {csv_path}')

"""## ✅ Summary
| Checkpoint | Location |
|------------|----------|
| Best model | `checkpoints/swinir/swinir_best.pth` |
| Results CSV | `sr_results.csv` |
| Visual grid | `visuals/swinir/swinir_qualitative.png` |

➡️ **Next:** Open `03_Inpainting_LaMa.ipynb`
"""