# -*- coding: utf-8 -*-
"""03_Inpainting_LaMa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0prFplkw6H3tJUSBzOPiirWsflHD-q7

# Notebook 3 - Image Inpainting with big-lama
**Paper:** A Corruption-Aware Image Restoration Framework for Spaceborne Optical Navigation

Steps:
1. Install LaMa and all dependencies
2. Download big-lama checkpoint
3. Mount Drive and set paths
4. Generate spacecraft-aware masks
5. Prepare LaMa input directory
6. Run inference
7. Qualitative results
8. Quantitative evaluation
9. Save to Drive

> Runtime: Runtime > Change runtime type > T4 GPU

## Step 1 - Install LaMa and All Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
print('\n> Cloning the repo')
!git clone https://github.com/advimman/lama.git

print('\n> Install dependencies')
!pip install wldhx.yadisk-direct
!pip install --upgrade pip
!pip uninstall --yes --quiet osqp
!pip install -U scikit-survival
!pip uninstall kornia -y
!pip install kornia --no-dependencies
!pip install kornia-rs
!pip install pytorch-lightning
!pip install hydra-core
!pip install webdataset
!pip install torch torchvision torchaudio torchtext
!pip install -r lama/requirements.txt --quiet
!pip install wget --quiet
!pip uninstall -y albumentations

print('\n> Changing the dir to:')
# %cd /content/lama

print('\n> Download the model')
!curl -LJO https://huggingface.co/smartywu/big-lama/resolve/main/big-lama.zip
!unzip big-lama.zip

print('>fixing opencv')
!pip uninstall opencv-python
!pip uninstall opencv-contrib-python

!pip install opencv-python

print('\n> Init mask-drawing code')
import base64, os
from IPython.display import HTML, Image
from google.colab.output import eval_js
from base64 import b64decode
import matplotlib.pyplot as plt
import numpy as np
import wget
from shutil import copyfile
import shutil



canvas_html = """
<style>
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
<canvas1 width=%d height=%d>
</canvas1>
<canvas width=%d height=%d>
</canvas>

<button class="button">Finish</button>
<script>
var canvas = document.querySelector('canvas')
var ctx = canvas.getContext('2d')

var canvas1 = document.querySelector('canvas1')
var ctx1 = canvas.getContext('2d')


ctx.strokeStyle = 'red';

var img = new Image();
img.src = "data:image/%s;charset=utf-8;base64,%s";
console.log(img)
img.onload = function() {
  ctx1.drawImage(img, 0, 0);
};
img.crossOrigin = 'Anonymous';

ctx.clearRect(0, 0, canvas.width, canvas.height);

ctx.lineWidth = %d
var button = document.querySelector('button')
var mouse = {x: 0, y: 0}

canvas.addEventListener('mousemove', function(e) {
  mouse.x = e.pageX - this.offsetLeft
  mouse.y = e.pageY - this.offsetTop
})
canvas.onmousedown = ()=>{
  ctx.beginPath()
  ctx.moveTo(mouse.x, mouse.y)
  canvas.addEventListener('mousemove', onPaint)
}
canvas.onmouseup = ()=>{
  canvas.removeEventListener('mousemove', onPaint)
}
var onPaint = ()=>{
  ctx.lineTo(mouse.x, mouse.y)
  ctx.stroke()
}

var data = new Promise(resolve=>{
  button.onclick = ()=>{
    resolve(canvas.toDataURL('image/png'))
  }
})
</script>
"""

def draw(imgm, filename='drawing.png', w=400, h=200, line_width=1):
  display(HTML(canvas_html % (w, h, w,h, filename.split('.')[-1], imgm, line_width)))
  data = eval_js("data")
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)

"""## Step 2 - Download big-lama Checkpoint"""

!pip install albumentations==0.5.2

"""## Step 3 - Mount Drive and Set Paths"""

from google.colab import drive
drive.mount('/content/drive')
import os

# Edit these to match your Drive
DRIVE_ROOT    = '/content/drive/MyDrive'
SPEEDPLUS_DIR = f'{DRIVE_ROOT}/speed/speed'
PROJECT_DIR   = f'{DRIVE_ROOT}/space_restoration'

WORK_DIR  = '/content/inpaint_work'
GT_DIR    = f'{WORK_DIR}/gt'
LAMA_IN   = f'{WORK_DIR}/lama_in'
LAMA_OUT  = f'{WORK_DIR}/lama_out'
VIS_DIR   = f'{PROJECT_DIR}/visuals/lama'

for d in [GT_DIR, LAMA_IN, LAMA_OUT, VIS_DIR]:
    os.makedirs(d, exist_ok=True)

all_imgs = sorted([f for f in os.listdir(SPEEDPLUS_DIR)
                   if f.endswith(('.jpg', '.png'))])
print(f'Found {len(all_imgs)} SPEED+ images')

"""## Step 4 - Spacecraft-Aware Mask Generator

Automatically generates masks without manual drawing:
- Detects spacecraft via Otsu thresholding on the near-black SPEED+ background
- Places 1-2 rectangular patches per image
- Hard limits: total coverage <= 25%, spacecraft overlap <= 40% per patch
- Three placement modes: edge, corner, free
- Saves masks as white=inpaint, black=keep (LaMa format)

"""

# Commented out IPython magic to ensure Python compatibility.
import random
import numpy as np
import cv2
import matplotlib.pyplot as plt
import sys
# %cd /content/lama
IMG_SIZE          = 256
MASK_MAX_COVERAGE = 0.25
SC_OVERLAP_LIMIT  = 0.40
MASK_N_MIN        = 1
MASK_N_MAX        = 2
MASK_MIN_RECT     = 15
MASK_MAX_RECT     = 70


def get_spacecraft_mask(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    _, sc = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    if sc.sum() < 100:
        _, sc = cv2.threshold(gray, 15, 255, cv2.THRESH_BINARY)
    k  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    sc = cv2.morphologyEx(sc, cv2.MORPH_CLOSE, k, iterations=2)
    sc = cv2.morphologyEx(sc, cv2.MORPH_OPEN,  k, iterations=1)
    return (sc > 0).astype(np.float32)


def sc_overlap_ratio(patch, sc_mask):
    sc_px = sc_mask.sum()
    return float((patch * sc_mask).sum() / sc_px) if sc_px > 0 else 0.0


def make_smart_mask(img_bgr, max_attempts=60):
    h, w    = img_bgr.shape[:2]
    mask    = np.zeros((h, w), dtype=np.float32)
    max_px  = int(h * w * MASK_MAX_COVERAGE)
    sc_mask = get_spacecraft_mask(img_bgr)
    strategy = random.choice(['edge', 'corner', 'free'])

    for _ in range(random.randint(MASK_N_MIN, MASK_N_MAX)):
        if mask.sum() >= max_px:
            break
        placed = False
        for _ in range(max_attempts):
            rh = random.randint(MASK_MIN_RECT, MASK_MAX_RECT)
            rw = random.randint(MASK_MIN_RECT, MASK_MAX_RECT)
            if strategy == 'edge':
                e = random.choice(['top', 'bottom', 'left', 'right'])
                if   e == 'top':    top, left = 0,    random.randint(0, w-rw)
                elif e == 'bottom': top, left = h-rh, random.randint(0, w-rw)
                elif e == 'left':   top, left = random.randint(0, h-rh), 0
                else:               top, left = random.randint(0, h-rh), w-rw
            elif strategy == 'corner':
                c    = random.choice(['tl', 'tr', 'bl', 'br'])
                top  = 0    if c in ('tl', 'tr') else h-rh
                left = 0    if c in ('tl', 'bl') else w-rw
            else:
                top  = random.randint(0, h-rh)
                left = random.randint(0, w-rw)
            patch = np.zeros((h, w), dtype=np.float32)
            patch[top:top+rh, left:left+rw] = 1.0
            if ((mask+patch).clip(0,1).sum() <= max_px and
                    sc_overlap_ratio(patch, sc_mask) <= SC_OVERLAP_LIMIT):
                mask = np.clip(mask + patch, 0, 1)
                placed = True
                break
        if not placed:
            fb = MASK_MIN_RECT
            t, l = random.choice([0, h-fb]), random.choice([0, w-fb])
            mask[t:t+fb, l:l+fb] = 1.0

    return (mask * 255).astype(np.uint8)


# Preview on 4 random images
preview_imgs = random.sample(all_imgs, min(4, len(all_imgs)))
fig, axes = plt.subplots(len(preview_imgs), 4, figsize=(18, 4*len(preview_imgs)))
if len(preview_imgs) == 1: axes = [axes]
for c, t in enumerate(['Original', 'Spacecraft (red)', 'Mask (white=inpaint)', 'Input to LaMa']):
    axes[0][c].set_title(t, fontsize=10, fontweight='bold')

for row, fname in enumerate(preview_imgs):
    bgr = cv2.imread(os.path.join(SPEEDPLUS_DIR, fname))
    bgr = cv2.resize(bgr, (IMG_SIZE, IMG_SIZE))
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    sc  = get_spacecraft_mask(bgr)
    msk = make_smart_mask(bgr)
    msk_f = msk.astype(np.float32) / 255.0
    sc_vis = rgb.astype(np.float32) / 255.0
    sc_vis[sc > 0, 0] = 1.0
    sc_vis[sc > 0, 1] *= 0.2
    sc_vis[sc > 0, 2] *= 0.2
    masked = rgb.copy()
    masked[msk > 0] = 0
    axes[row][0].imshow(rgb)
    axes[row][1].imshow(sc_vis.clip(0, 1))
    axes[row][2].imshow(msk, cmap='gray', vmin=0, vmax=255)
    axes[row][2].set_xlabel(
        'Cov: {:.1f}%  SC: {:.1f}%'.format(
            msk_f.mean()*100, sc_overlap_ratio(msk_f, sc)*100),
        fontsize=8)
    axes[row][3].imshow(masked)
    for ax in axes[row]: ax.axis('off')

plt.suptitle('Spacecraft-Aware Mask Preview', fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig(f'{PROJECT_DIR}/mask_preview.png', dpi=120, bbox_inches='tight')
plt.show()
print('Mask rules: max {}% coverage, max {}% SC overlap, {}-{} patches, max {}px'.format(
    int(MASK_MAX_COVERAGE*100), int(SC_OVERLAP_LIMIT*100),
    MASK_N_MIN, MASK_N_MAX, MASK_MAX_RECT))

"""## Step 5 - Prepare LaMa Input Directory

predict.py expects image and mask in the same folder:
```
lama_in/
  img000001.png
  img000001_mask001.png
```

"""

from tqdm import tqdm

MAX_IMAGES = None  # set to integer e.g. 200 for a quick test

run_imgs = all_imgs[:MAX_IMAGES] if MAX_IMAGES else all_imgs
skipped  = 0

for fname in tqdm(run_imgs, desc='Building LaMa input dir'):
    # Strip 'Copy of ' prefix that Google Drive sometimes adds
    stem = os.path.splitext(fname)[0].replace('Copy of ', '').strip()
    bgr  = cv2.imread(os.path.join(SPEEDPLUS_DIR, fname))
    if bgr is None:
        skipped += 1
        continue
    bgr = cv2.resize(bgr, (IMG_SIZE, IMG_SIZE))
    msk = make_smart_mask(bgr)
    cv2.imwrite(os.path.join(GT_DIR,  stem + '.png'), bgr)
    cv2.imwrite(os.path.join(LAMA_IN, stem + '.png'), bgr)
    cv2.imwrite(os.path.join(LAMA_IN, stem + '_mask001.png'), msk)

n = len([f for f in os.listdir(LAMA_IN) if '_mask' not in f])
print(f'Done: {n} image+mask pairs ready  |  skipped: {skipped}')
print('Sample files:', sorted(os.listdir(LAMA_IN))[:4])

!pip uninstall albumentations -y -q
!pip install albumentations==0.5.2 -q

# Patch imgaug source file before importing
imgaug_path = '/usr/local/lib/python3.12/dist-packages/imgaug/imgaug.py'
with open(imgaug_path, 'r') as f:
    src = f.read()

if 'np.sctypes' in src:
    src = src.replace(
        'NP_FLOAT_TYPES = set(np.sctypes["float"])',
        'NP_FLOAT_TYPES = set([np.float16, np.float32, np.float64])'
    )
    with open(imgaug_path, 'w') as f:
        f.write(src)
    print('imgaug.py patched')
else:
    print('Already patched')

# Patch lama aug.py
aug_path = '/content/lama/saicinpainting/training/data/aug.py'
with open(aug_path, 'r') as f:
    src = f.read()

if 'DualIAATransform' in src:
    src = src.replace(
        'from albumentations import DualIAATransform, to_tuple',
        'from albumentations import DualTransform as DualIAATransform, to_tuple'
    )
    with open(aug_path, 'w') as f:
        f.write(src)
    print('aug.py patched')
else:
    print('Already patched')

imgaug_path = '/usr/local/lib/python3.12/dist-packages/imgaug/imgaug.py'
with open(imgaug_path, 'r') as f:
    src = f.read()

# Replace ALL np.sctypes references in one go
replacements = {
    'NP_FLOAT_TYPES = set(np.sctypes["float"])':
        'NP_FLOAT_TYPES = set([np.float16, np.float32, np.float64])',
    'NP_INT_TYPES = set(np.sctypes["int"])':
        'NP_INT_TYPES = set([np.int8, np.int16, np.int32, np.int64])',
    'NP_UINT_TYPES = set(np.sctypes["uint"])':
        'NP_UINT_TYPES = set([np.uint8, np.uint16, np.uint32, np.uint64])',
}

for old, new in replacements.items():
    src = src.replace(old, new)

with open(imgaug_path, 'w') as f:
    f.write(src)

# Verify no np.sctypes remain
remaining = [l for l in src.split('\n') if 'np.sctypes' in l]
if remaining:
    print('Still has sctypes:', remaining)
else:
    print('All np.sctypes patched successfully')

trainer_path = '/content/lama/saicinpainting/training/trainers/__init__.py'
with open(trainer_path, 'r') as f:
    src = f.read()

src = src.replace(
    'state = torch.load(path, map_location=map_location)',
    'state = torch.load(path, map_location=map_location, weights_only=False)'
)

with open(trainer_path, 'w') as f:
    f.write(src)

print('Patched:', 'weights_only=False' in open(trainer_path).read())

import os
os.environ['LAMA_CKPT'] = '/content/lama/big-lama'
os.environ['LAMA_IN']   = '/content/inpaint_work/lama_in'
os.environ['LAMA_OUT']  = '/content/inpaint_work/lama_out'

!PYTHONPATH=/content/lama python /content/lama/bin/predict.py \
    model.path=$LAMA_CKPT \
    indir=$LAMA_IN \
    outdir=$LAMA_OUT \
    dataset.img_suffix=.png

out_files = sorted([f for f in os.listdir('/content/inpaint_work/lama_out') if f.endswith('.png')])
print(f'Done: {len(out_files)} output images')
print('Outputs:', out_files[:3])

"""## Step 6 - Run big-lama Inference"""

# Commented out IPython magic to ensure Python compatibility.

"""
import os

# %cd /content/lama


!PYTHONPATH=/content/lama python /content/lama/bin/predict.py \
    model.path="/content/lama/big-lama " \
    indir="/content/inpaint_work/lama_in "\
    outdir="/content/inpaint_work/lama_out" \
    dataset.img_suffix=.png

out_files = sorted([f for f in os.listdir("/content/inpaint_work/lama_out") if f.endswith('.png')])
print(f'Inference done: {len(out_files)} output images')
print('Sample outputs:', out_files[:3])
if len(out_files) == 0:
    print('WARNING: No outputs. Check the log above for errors.')
"""

"""## Step 7 - Qualitative Results"""

import math
import matplotlib.pyplot as plt

out_files = sorted([f for f in os.listdir(LAMA_OUT) if f.endswith('.png')])
print('Sample output filenames:', out_files[:3])

n_show  = min(6, len(out_files))
samples = random.sample(out_files, n_show)

fig, axes = plt.subplots(n_show, 4, figsize=(18, 4*n_show))
if n_show == 1: axes = [axes]
for c, t in enumerate(['GT (original)', 'Mask (white=inpainted)',
                        'LaMa Output', '|GT - Output| error']):
    axes[0][c].set_title(t, fontsize=11, fontweight='bold')

for row, fname in enumerate(samples):
    stem     = os.path.splitext(fname)[0].replace('_mask001', '')
    gt_path  = os.path.join(GT_DIR,  stem + '.png')
    msk_path = os.path.join(LAMA_IN, stem + '_mask001.png')
    out_path = os.path.join(LAMA_OUT, fname)
    gt  = cv2.cvtColor(cv2.imread(gt_path),  cv2.COLOR_BGR2RGB)
    msk = cv2.imread(msk_path, cv2.IMREAD_GRAYSCALE)
    out = cv2.cvtColor(cv2.imread(out_path), cv2.COLOR_BGR2RGB)
    diff = np.abs(gt.astype(np.float32) - out.astype(np.float32)).mean(axis=2)
    mse  = np.mean((gt.astype(np.float32)/255 - out.astype(np.float32)/255)**2)
    psnr = 10*math.log10(1/mse) if mse > 1e-10 else 100
    axes[row][0].imshow(gt)
    axes[row][1].imshow(msk, cmap='gray', vmin=0, vmax=255)
    axes[row][2].imshow(out)
    axes[row][2].set_xlabel('PSNR = {:.2f} dB'.format(psnr), fontsize=9)
    axes[row][3].imshow(diff, cmap='hot', vmin=0, vmax=40)
    for ax in axes[row]: ax.axis('off')

plt.suptitle('big-lama Inpainting - SPEED+ Qualitative Results',
             fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
fig_path = f'{VIS_DIR}/lama_qualitative.png'
plt.savefig(fig_path, dpi=120, bbox_inches='tight')
plt.show()
print('Figure saved to ' + fig_path)

"""## Step 8 - Quantitative Evaluation (PSNR and SSIM)"""

import csv, math
import numpy as np
from skimage.metrics import structural_similarity as skssim
from tqdm import tqdm

out_files = sorted([f for f in os.listdir(LAMA_OUT) if f.endswith('.png')])
results   = []

for fname in tqdm(out_files, desc='Evaluating'):
    stem     = os.path.splitext(fname)[0].replace('_mask001', '')
    gt_path  = os.path.join(GT_DIR,  stem + '.png')
    msk_path = os.path.join(LAMA_IN, stem + '_mask001.png')
    out_path = os.path.join(LAMA_OUT, fname)
    if not all(os.path.exists(p) for p in [gt_path, msk_path, out_path]):
        continue
    gt   = cv2.imread(gt_path).astype(np.float32)  / 255.0
    out  = cv2.imread(out_path).astype(np.float32) / 255.0
    msk  = cv2.imread(msk_path, cv2.IMREAD_GRAYSCALE).astype(np.float32) / 255.0
    baseline = gt.copy()
    baseline[msk > 0.5] = 0.0
    mse_out  = np.mean((gt - out)**2)
    mse_base = np.mean((gt - baseline)**2)
    results.append({
        'name':          stem,
        'psnr_baseline': 10*math.log10(1/mse_base) if mse_base > 1e-10 else 100,
        'psnr_lama':     10*math.log10(1/mse_out)  if mse_out  > 1e-10 else 100,
        'ssim_baseline': skssim(baseline, gt, data_range=1.0, channel_axis=2),
        'ssim_lama':     skssim(out,      gt, data_range=1.0, channel_axis=2),
        'mask_coverage': float(msk.mean()),
    })

avg = {k: np.mean([r[k] for r in results]) for k in results[0] if k != 'name'}
print('=' * 58)
print('  big-lama - SPEED+ Inpainting Evaluation')
print('=' * 58)
print('  {:<28} {:>10} {:>10}'.format('Method', 'PSNR (dB)', 'SSIM'))
print('-' * 52)
print('  {:<28} {:>10.2f} {:>10.4f}'.format('Masked Input (baseline)',
      avg['psnr_baseline'], avg['ssim_baseline']))
print('  {:<28} {:>10.2f} {:>10.4f}'.format('big-lama',
      avg['psnr_lama'], avg['ssim_lama']))
print('=' * 58)
print('  Avg mask coverage: {:.1f}%'.format(avg['mask_coverage']*100))
print('  Images evaluated : {}'.format(len(results)))

csv_path = f'{PROJECT_DIR}/inpaint_results.csv'
with open(csv_path, 'w', newline='') as f:
    w = csv.DictWriter(f, fieldnames=results[0].keys())
    w.writeheader()
    w.writerows(results)
print('CSV saved to ' + csv_path)

"""## Step 9 - Save All Outputs to Drive"""

import shutil
from tqdm import tqdm

DRIVE_OUT = f'{PROJECT_DIR}/inpaint/lama_output'
os.makedirs(DRIVE_OUT, exist_ok=True)

out_files = [f for f in os.listdir(LAMA_OUT) if f.endswith('.png')]
for fname in tqdm(out_files, desc='Copying to Drive'):
    shutil.copy(os.path.join(LAMA_OUT, fname),
                os.path.join(DRIVE_OUT, fname))

print('All outputs saved:')
print('  Inpainted images : ' + DRIVE_OUT + ' (' + str(len(out_files)) + ' files)')
print('  Metrics CSV      : ' + PROJECT_DIR + '/inpaint_results.csv')
print('  Qualitative fig  : ' + VIS_DIR + '/lama_qualitative.png')
print('  Mask preview     : ' + PROJECT_DIR + '/mask_preview.png')